{
 "title": "Accelerator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Run number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"run_no\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "Shot number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"shot_no\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "MR cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"mr_cycle\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "MR power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"dcct_073_1_val_mrpwr\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "MR P3 intensity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"mr_p3_intensity\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "HD mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"opr_mode\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "SX duty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"sxopr_d2_val_duty\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "SX spill length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"sxopr_d2_val_splen\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "SX extraction efficiency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"sxopr_d2_val_exteffi\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "HD power (RGICM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"rgicm_power\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "HD intensity (SYIM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"syim_intensity\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "HD intensity (RGICM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"rgicm_intensity\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"mr_p3_intensity\" or r._field == \"rgicm_intensity\" or r._field == \"syim_intensity\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"sxopr_d2_val_duty\" or r._field == \"sxopr_d2_val_exteffi\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "HD B intensity (BDMPIM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"bdmpim_intensity\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "HD B intensity (BIC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acc\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"bic_intensity\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n"
    }
   ]
  }
 ]
}