{
 "title": "ESS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "ESS1 POS VMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"pos_vmon\")\n  |> filter(fn: (r) => r._measurement == \"ess1\")\n  |> aggregateWindow(every: 1m, fn: min)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1000)\n"
    }
   ]
  },
  {
   "title": "ESS1 NEG VMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"neg_vmon\")\n  |> filter(fn: (r) => r._measurement == \"ess1\")\n  |> aggregateWindow(every: 1m, fn: min)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS1 POS IMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"pos_imon\")\n  |> filter(fn: (r) => r._measurement == \"ess1\")\n  |> aggregateWindow(every: 1m, fn: max)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS1 NEG IMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"neg_imon\")\n  |> filter(fn: (r) => r._measurement == \"ess1\")\n  |> aggregateWindow(every: 1m, fn: max)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS1 VACUUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"ccg_pmon\")\n  |> filter(fn: (r) => r._measurement == \"ess1\")\n  |> aggregateWindow(every: 5m, fn: mean)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS2 POS VMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"pos_vmon\")\n  |> filter(fn: (r) => r._measurement == \"ess2\")\n  |> aggregateWindow(every: 1m, fn: min)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS2 NEG VMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"neg_vmon\")\n  |> filter(fn: (r) => r._measurement == \"ess2\")\n  |> aggregateWindow(every: 1m, fn: min)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS2 POS IMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"pos_imon\")\n  |> filter(fn: (r) => r._measurement == \"ess2\")\n  |> aggregateWindow(every: 1m, fn: max)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS2 NEG IMON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"neg_imon\")\n  |> filter(fn: (r) => r._measurement == \"ess2\")\n  |> aggregateWindow(every: 1m, fn: max)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS2 VACUUM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field == \"ccg_pmon\")\n  |> filter(fn: (r) => r._measurement == \"ess2\")\n  |> aggregateWindow(every: 5m, fn: mean)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS VMON",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field =~ /.vmon/)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n // |> aggregateWindow()\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS IMON",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µA" } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field =~ /.imon/)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS VACUUM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._field =~ /.pmon/)\n//  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n//  |> limit(n: 1)\n"
    }
   ]
  },
  {
   "title": "ESS every hour",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"ess\")\n  |> range(start: -12h)\n//  |> filter(fn: (r) => r._measurement == \"ess1\")\n  |> aggregateWindow(every: 1h, fn: mean)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n//  |> keep(columns: [\"_time\", \"pos_vset\", \"pos_vmon\", \"neg_vset\", \"neg_vmon\", \"pos_imon\", \"neg_imon\", \"ccg_pmon\"])\n//  |> limit(n: 1)\n"
    }
   ]
  }
 ]
}