{
 "title": "System resources",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_user\" and r.cpu == \"cpu-total\")\n  |> drop(columns: [\"environment\"])\n//  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\")\n  |> drop(columns: [\"environment\"])\n // |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"net\" and (r._field == \"bytes_recv\" or r._field == \"bytes_sent\"))\n  |> derivative(unit: 1s, nonNegative: true)\n//  |> aggregateWindow(every: 1m, fn: max)\n  |> map(fn: (r) => ({\n    r with _value: if r._field == \"bytes_sent\" then r._value * -1.0 else r._value\n  }))\n//  |> map(fn: (r) => ({\n//    r with label: if r._interface == \"enp193s0\" then \"daq\" else \"unk\"\n//  }))\n  |> keep(columns: [\"_time\", \"interface\", \"host\", \"label\", \"_field\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"diskio\" and (r._field == \"read_bytes\" or r._field == \"write_bytes\"))\n  |> derivative(unit: 1s, nonNegative: true)\n// |> aggregateWindow(every: 1m, fn: max)\n  |> map(fn: (r) => ({\n    r with _value: if r._field == \"read_bytes\" then r._value * -1.0 else r._value\n  }))\n  |> drop(columns: [\"environment\"])\n"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"sensors\" and r._field == \"temp_input\")\n//  |> group(columns: [\"chip\", \"feature\"])\n//  |> max(column: \"_value\")\n  |> group(columns: [\"chip\", \"host\"])\n  //  |> map(fn: (r) => ({\n  //  r with _value: if r._field == \"bytes_sent\" then r._value * -1.0 else r._value\n  //}))\n  |> aggregateWindow(every: 20s, fn: max)\n  |> keep(columns: [\"_time\", \"chip\", \"_value\", \"host\"])\n//  |> drop(columns: [\"environment\", \"_start\", \"_stop\", \"feature\"])\n"
    }
   ]
  }
 ]
}