{
 "title": "Threshold",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "VMon",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"kikusui\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r._measurement == \"pmx\" and r._field == \"vmon\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"device\", \"_value\"])"
    }
   ]
  },
  {
   "title": "IMon",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"kikusui\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r._measurement == \"pmx\" and r._field == \"imon\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"device\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "V895 vme05 0xdc160000-ch0 (BAC)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"v895\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r._field == \"threshold\")\n  |> filter(fn: (r) => r.host == \"vme05\")\n  |> filter(fn: (r) => r.vme_address == \"dc160000\")\n  |> filter(fn: (r) => r.channel == \"00\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"channel\", \"_value\"])"
    }
   ]
  },
  {
   "title": "V895 ctrl2 0xdc190000-ch0 (AC1-SUM)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"v895\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r._field == \"threshold\")\n  |> filter(fn: (r) => r.host == \"ctrl2\")\n  |> filter(fn: (r) => r.vme_address == \"0xdc190000\")\n  |> filter(fn: (r) => r.channel == \"00\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"channel\", \"_value\"])"
    }
   ]
  },
  {
   "title": "V895 ctrl2 0xdc100000 (WC)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"v895\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r._field == \"threshold\")\n  |> filter(fn: (r) => r.host == \"ctrl2\")\n  |> filter(fn: (r) => r.vme_address == \"0xdc100000\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"channel\", \"_value\"])"
    }
   ]
  }
 ]
}